import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useState } from 'react'

export default function Home() {
  const [data, setData] = useState({
    activity: "",
    type: "",
    participants: ""
  });

  async function boredFetch() {
    const res = await fetch(`https://www.boredapi.com/api/activity/`)
    const data = await res.json()
    setData(data);
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        <h1>Activity: {data.activity}</h1>
        <p>Type: {data.type}</p>
        <p>Participants: {data.participants}</p>

        <button onClick={boredFetch}>Get Activity</button>

      </main>
    </>
  )
}
